In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [82]:
toxity = pd.read_csv('toxity_per_attribute.csv', delimiter = ',', low_memory = False)

In [96]:
toxity.tail()

,Wiki_ID,TOXICITY,lesbian,gay,bisexual,transgender,trans,queer,lgbt,lgbtq,...,older,young,younger,teenage,millenial,middle aged,elderly,blind,deaf,paralyzed
76560,76559.0,0.341937,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76561,76560.0,0.959019,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76562,76561.0,0.026080,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76563,76562.0,0.967042,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76564,76563.0,0.096347,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [84]:
toxity.columns

Index(['Wiki_ID', 'TOXICITY', 'lesbian', 'gay', 'bisexual', 'transgender',
       'trans', 'queer', 'lgbt', 'lgbtq', 'homosexual', 'straight',
       'heterosexual', 'male', 'female', 'nonbinary', 'african',
       'african american', 'black', 'white', 'european', 'hispanic', 'latino',
       'latina', 'latinx', 'mexican', 'canadian', 'american', 'asian',
       'indian', 'middle eastern', 'chinese', 'japanese', 'christian',
       'muslim', 'jewish', 'buddhist', 'catholic', 'protestant', 'sikh',
       'taoist', 'old', 'older', 'young', 'younger', 'teenage', 'millenial',
       'middle aged', 'elderly', 'blind', 'deaf', 'paralyzed'],
      dtype='object')

In [42]:
toxity.dtypes

Wiki_ID             float64
TOXICITY            float64
lesbian              object
gay                  object
bisexual             object
transgender          object
trans                object
queer                object
lgbt                 object
lgbtq                object
homosexual           object
straight             object
heterosexual         object
male                 object
female               object
nonbinary            object
african              object
african american     object
black                object
white                object
european             object
hispanic             object
latino               object
latina               object
latinx               object
mexican              object
canadian             object
american             object
asian                object
indian               object
middle eastern       object
chinese              object
japanese             object
christian            object
muslim               object
jewish               object
buddhist             object
catholic             object
protestant           object
sikh                 object
taoist               object
old                  object
older                object
young                object
younger              object
teenage              object
millenial            object
middle aged          object
elderly              object
blind                object
deaf                 object
paralyzed            object
dtype: object

In [87]:
toxity_2 = toxity.replace(['False'], 'Hello')

In [113]:
toxity_2

,Wiki_ID,TOXICITY,lesbian,gay,bisexual,transgender,trans,queer,lgbt,lgbtq,...,older,young,younger,teenage,millenial,middle aged,elderly,blind,deaf,paralyzed
0,0.0,0.096492,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1.0,0.017991,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2.0,0.150298,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3.0,0.065861,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4.0,0.667166,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76560,76559.0,0.341937,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76561,76560.0,0.959019,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76562,76561.0,0.026080,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76563,76562.0,0.967042,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76564,76563.0,0.096347,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [81]:
toxity.dtypes

Wiki_ID             float64
TOXICITY            float64
lesbian              object
gay                  object
bisexual             object
transgender          object
trans                object
queer                object
lgbt                 object
lgbtq                object
homosexual           object
straight             object
heterosexual         object
male                 object
female               object
nonbinary            object
african              object
african american     object
black                object
white                object
european             object
hispanic             object
latino               object
latina               object
latinx               object
mexican              object
canadian             object
american             object
asian                object
indian               object
middle eastern       object
chinese              object
japanese             object
christian            object
muslim               object
jewish               object
buddhist             object
catholic             object
protestant           object
sikh                 object
taoist               object
old                  object
older                object
young                object
younger              object
teenage              object
millenial            object
middle aged          object
elderly              object
blind                object
deaf                 object
paralyzed            object
dtype: object

In [71]:
#toxity_red = toxity[toxity.replace({'False': False, 'True': True}).any(1)]

In [125]:
#toxity = toxity.replace('False','Green')
toxity_2[['lesbian']] = toxity[['lesbian']].replace(to_replace = 'FALSE', value = 'Green')
#toxity[toxity == 'False'] = 'Green'
toxity_2.lesbian

#df.replace(to_replace = 0.0, value = -1, inplace = True)

0        False
1        False
2        False
3        False
4        False
         ...
76560    False
76561    False
76562    False
76563    False
76564    False
Name: lesbian, Length: 76565, dtype: object

In [124]:
#toxity_bool = toxity["lesbian"].replace({"FALSE": False})

In [35]:
toxity_bool.dtypes

dtype('O')

In [36]:
toxity_bool

0        False
1        False
2        False
3        False
4        False
         ...
76560    False
76561    False
76562    False
76563    False
76564    False
Name: lesbian, Length: 76565, dtype: object

In [101]:
colors = {'first_set':  ['Green','Green','Green','Blue','Blue','Red','Red','Red'],
          'second_set': ['Yellow','Yellow','Yellow','White','White','Blue','Blue','Blue']
         }

df = pd.DataFrame(colors, columns= ['first_set','second_set'])
df
df = df.replace(['Blue'],'Green')

df

  first_set second_set
0     Green     Yellow
1     Green     Yellow
2     Green     Yellow
3     Green      White
4     Green      White
5       Red      Green
6       Red      Green
7       Red      Green